### ISSUE TITLE
16x16 sprite support

### ISSUE THREAD

**Issue by schme16** [battlecoder/pngb#1]
I'd love to be able to export 16x16 sprites

**Comment by battlecoder** [comment]
Hi! As far as I know the biggest sprite size the GB supports is 8x16. Larger sprites were created by moving and updating several smaller sprites together.

**Comment by schme16** [comment]
Ahh, you may be right.

I'm using GBDK + [ZBG](https://github.com/Zal0/ZGB) to create my game- they recommend using Harry Mulder's Gameboy Map Builder, and more related to this, Harry Mulder's Gameboy Tile Designer.

The GBTD has options that allow create and using up to 32x32 sprites.
![image](https://user-images.githubusercontent.com/116081/59197422-a3444a00-8bd4-11e9-9d03-e439a90567d4.png)

Being a newbie I assumed it was just natively supported, but there may be some engine trickery being done behind the scenes.

Thanks for checking the issue for me anyways!

**Comment by battlecoder** [comment]
No prob. I just took a look at the output of GBTD and it basically creates a file with the pixel data. Because of this the editor could in theory allow for any size, considering that the output it generates does not attempt to load that into the sprite memory (unless I missed something). So it's up to ZBG in this case (given that it supports 16x16 sprites) to load that data into two 8x16 sprite "slots" (or four 8x8) in memory and handle them together as a single 16x16 sprite.

At any rate, I'm glad to hear from people still making gameboy games!

**Comment by schme16** [comment]
That would make sense, thanks so much for taking the time to check it all out though, I really appreciate the effort!

I'll close the issue off.
